"""Pure helpers for Textual answer command handling."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Generic, Literal, Protocol, TypeVar

from trinity.textual_app import presenters as textual_presenters
from trinity.textual_app.command_parsers import parse_answer_args


AnswerSeverity = Literal["info", "warning"]
OutcomeT = TypeVar("OutcomeT")


class AnswerWorkflowController(Protocol[OutcomeT]):
    """Workflow controller surface required by `/answer`."""

    def answer_question(
        self,
        question_id: str,
        answer: str,
        *,
        replace: bool = False,
    ) -> OutcomeT:
        """Record a free-form answer for a question."""

    def answer_question_option(
        self,
        option_index: str,
        *,
        question_selector: str = "next",
        replace: bool = False,
    ) -> OutcomeT:
        """Record a numbered option answer for a question."""


@dataclass(frozen=True)
class AnswerResultPresentation:
    """Presentation flags derived from an answer workflow outcome message."""

    message: str
    severity: AnswerSeverity
    empty: bool


@dataclass(frozen=True)
class AnswerCommandPresentation:
    """Prepared local command result for `/answer`."""

    title: str
    body: str
    severity: AnswerSeverity
    empty: bool = False
    action_hint: str = ""


@dataclass(frozen=True)
class AnswerCommandRun(Generic[OutcomeT]):
    """Controller outcome or local parse error generated by `/answer`."""

    outcome: OutcomeT | None = None
    presentation: AnswerCommandPresentation | None = None


def answer_result_presentation(
    message: str | None,
) -> AnswerResultPresentation | None:
    """Return local command presentation state for an answer outcome message."""
    if not message:
        return None
    failed = message.startswith("No ")
    return AnswerResultPresentation(
        message=message,
        severity="warning" if failed else "info",
        empty=failed,
    )


def answer_error_command_presentation(
    error: str,
    action_hint: str,
    *,
    lang: str = "en",
) -> AnswerCommandPresentation:
    """Return the local command result payload for an answer parse error."""
    return AnswerCommandPresentation(
        title=textual_presenters.answer_title(lang=lang),
        body=error,
        severity="warning",
        empty=True,
        action_hint=action_hint,
    )


def answer_result_command_presentation(
    presentation: AnswerResultPresentation,
    *,
    lang: str = "en",
) -> AnswerCommandPresentation:
    """Return the local command result payload for an answer outcome."""
    return AnswerCommandPresentation(
        title=textual_presenters.answer_title(lang=lang),
        body=textual_presenters.workflow_outcome_message_markdown(
            presentation.message,
            lang=lang,
        ),
        severity=presentation.severity,
        empty=presentation.empty,
    )


def answer_message_command_presentation(
    message: str | None,
    *,
    lang: str = "en",
) -> AnswerCommandPresentation | None:
    """Return the local command result payload for an answer outcome message."""
    presentation = answer_result_presentation(message)
    if presentation is None:
        return None
    return answer_result_command_presentation(presentation, lang=lang)


def run_answer_command(
    args: list[str],
    controller: AnswerWorkflowController[OutcomeT],
    *,
    lang: str = "en",
) -> AnswerCommandRun[OutcomeT]:
    """Parse `/answer` arguments and route to the workflow controller."""
    parsed = parse_answer_args(args, lang=lang)
    if parsed.error:
        return AnswerCommandRun(
            presentation=answer_error_command_presentation(
                parsed.error,
                parsed.action_hint,
                lang=lang,
            )
        )
    if parsed.option_index:
        return AnswerCommandRun(
            outcome=controller.answer_question_option(
                parsed.option_index,
                replace=parsed.replace,
            )
        )
    return AnswerCommandRun(
        outcome=controller.answer_question(
            parsed.question_selector,
            parsed.answer,
            replace=parsed.replace,
        )
    )
